name: build Azul-Zulu-OpenJDK-java
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - Azul-Zulu-OpenJDK-java8/**
      - Azul-Zulu-OpenJDK-java11/**
      - Azul-Zulu-OpenJDK-java17/**
      - Azul-Zulu-OpenJDK-java21/**
      - Azul-Zulu-OpenJDK-java25/**
jobs:
  push:
    name: "yolks:azul-zulu-openjdk-java${{ matrix.tag }}/${{ matrix.arch }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '8'
          - '11'
          - '17'
          - '21'
          - '25'
        arch:
          - 'aarch64'
          - 'amd64'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUBTOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./IBM-Semeru-Runtimes-java${{ matrix.tag }}
          file: ./IBM-Semeru-Runtimes-java${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/mg8853/yolks:ibm-semeru-runtimes-java${{ matrix.tag }}
