name: build Oracle-GraalVM-java
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - Oracle-GraalVM-java17/**
      - Oracle-GraalVM-java21/**
      - Oracle-GraalVM-java25/**
jobs:
  push:
    name: "yolks:oracle-graalvm-java${{ matrix.tag }}/${{ matrix.arch }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '17'
          - '21'
          - '25'
        arch:
          - 'aarch64'
          - 'amd64'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUBTOKEN }}


      - name: Build&Push(aarch64)-Java17
        if: matrix.arch == 'aarch64' && matrix.tag == '17'
        uses: docker/build-push-action@v2
        with:
          context: ./Oracle-GraalVM-java${{ matrix.tag }}/aarch64
          file: ./Oracle-GraalVM-java${{ matrix.tag }}/aarch64/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/mg8853/yolks_aarch64:oracle-graalvm-java${{ matrix.tag }}-aarch64
      - name: Build&Push(amd64)-Java17
        if: matrix.arch == 'amd64' && matrix.tag == '17'
        uses: docker/build-push-action@v2
        with:
          context: ./Oracle-GraalVM-java${{ matrix.tag }}/amd64
          file: ./Oracle-GraalVM-java${{ matrix.tag }}/amd64/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/mg8853/yolks_amd64:oracle-graalvm-java${{ matrix.tag }}-amd64


      - name: Build&Push(aarch64)-Java21
        if: matrix.arch == 'aarch64' && matrix.tag == '21'
        uses: docker/build-push-action@v2
        with:
          context: ./Oracle-GraalVM-java${{ matrix.tag }}/aarch64
          file: ./Oracle-GraalVM-java${{ matrix.tag }}/aarch64/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/mg8853/yolks_aarch64:oracle-graalvm-java${{ matrix.tag }}-aarch64
      - name: Build&Push(amd64)-Java21
        if: matrix.arch == 'amd64' && matrix.tag == '21'
        uses: docker/build-push-action@v2
        with:
          context: ./Oracle-GraalVM-java${{ matrix.tag }}/amd64
          file: ./Oracle-GraalVM-java${{ matrix.tag }}/amd64/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/mg8853/yolks_amd64:oracle-graalvm-java${{ matrix.tag }}-amd64


      - name: Build&Push(aarch64)-Java25
        if: matrix.arch == 'aarch64' && matrix.tag == '25'
        uses: docker/build-push-action@v2
        with:
          context: ./Oracle-GraalVM-java${{ matrix.tag }}/aarch64
          file: ./Oracle-GraalVM-java${{ matrix.tag }}/aarch64/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/mg8853/yolks_aarch64:oracle-graalvm-java${{ matrix.tag }}-aarch64
      - name: Build&Push(amd64)-Java25
        if: matrix.arch == 'amd64' && matrix.tag == '25'
        uses: docker/build-push-action@v2
        with:
          context: ./Oracle-GraalVM-java${{ matrix.tag }}/amd64
          file: ./Oracle-GraalVM-java${{ matrix.tag }}/amd64/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/mg8853/yolks_amd64:oracle-graalvm-java${{ matrix.tag }}-amd64

